config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  resources :sessions
  resources :articles
  resources :categories
  resources :users
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
    

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true
  validates :content, presence: true
  validates :categories, presence: true
  
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
   has_secure_password
   has_many :articles

   validates_uniqueness_of :email
   validates :name, presence: true
   validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories 

  private
  def get_categories
    @categories = Category.all.order(:name)
  end
  def articles_count
    Article.all.count
  end
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :authorize, only: [:new]
  
  def index
    @articles = Article.order(updated_at: :desc).limit(25)
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
      if @article.save
        redirect_to @article
      else
      render "new"
    end
  end
  
  
  private
    def article_params
      params.require(:article).permit(:title, :content, :category_ids => [])
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:name)
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(category_params)
      flash[:notice] = 'The category is successfully updated!'
      redirect_to edit_category_path
    end
  end


  def destroy
    Category.find(params[:id]).destroy
    redirect_to :action => 'index'
  end  
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) # get this for free from has_secure_password
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Thank you for signing up"
      else
        render "new"
      end
    end

    private 
      def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @recent_articles = Article.order(updated_at: :desc).first(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path, string)
    if current_page?(link_path)
      string + " active"
    else
      string
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
  <h1>Articles</h1>
  <h4>By most recent</h4>
  <% @articles.each do |article| %>
    <div>
      <h4><%= link_to article.title, article %></h4>
      <strong>Published:</strong> <em><%= article.created_at.strftime('%d, %b, %Y') %></em>&nbsp;&nbsp;&nbsp;
      <strong>Category:</strong> <% article.categories.each do |category| %>
                  <em><%= category.name %></em>&nbsp;
                <% end %>      
      <p><%= truncate(article.content, length: 200) %></p></br>
    </div>
  <% end %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
  <% if @article.errors.any? %>
  <div class="error_messages">
      <h2>You're missing some fields</h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </br>
  <%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div>
  <h1><%= @article.title %></h1>
  <p><strong>Published:</strong> <em><%= @article.created_at.strftime('%d, %b, %Y') %></em></p>
  <p><strong>Filed under:</strong> <% @article.categories.each do |category| %>
    <em><%= category.name %></em>&nbsp;<% end %>
  </p>
  <div><%= @article.content %></div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>


<%= render :partial => 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<% @categories.each do |category| %>
  <div>
    <h5><%= link_to category.name, category %></h5>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
  <h1><%= @category.name %></h1>
  <p><strong>Created:</strong> <em><%= @category.created_at.strftime('%d, %b, %Y') %></em></p>
  <h3>Articles under this category</h3>
  <p>
    <% @category.articles.order(:updated_at).each do |article| %>
      <p><%= link_to article.title, article %></p>
    <% end %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= bootstrap_flash %>
  <div class="nav navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
		<a>Menu</a>
	  </button>
	</div>
    <div class="collapse navbar-collapse" id="collapse">  
      <div class="container">
	    <a class="navbar-brand">Wikiful</a>
        <div class="btn-group"> 
          <%= link_to "Home", root_path, class: is_active?(root_path, "brand btn btn-default navbar-btn") %>        
          <%= link_to "Articles", articles_path, class: is_active?(articles_path, "btn btn-default navbar-btn") %>
          <%= link_to "Categories", categories_path, class: is_active?(categories_path, "btn btn-default navbar-btn") %>
          <button class="btn btn-default navbar-btn dropdown-toggle" type="button" data-toggle="dropdown">     
      	    About <span class="caret"></span> 
      	  </button>
      	  <div class="dropdown-menu pull-right" role="menu">
      		<p>
      	      Wikiful is yet another wiki.</br>
      	      If you are unhappy about it's</br> 
      	      lack of features you are welcome to</br>
      	      take it and get forked.
      		</p>
      	  </div>
        </div>
        <div class="btn-group">
      	  <%= link_to "New", new_article_path, class: is_active?(new_article_path, "btn btn-default navbar-btn") %>
      	</div>
        <div class="navbar-right">
          <% if current_user %>
            <p class="navbar-text"><%= current_user.email %></p>
            <%= link_to "Log Out", logout_path, :class => 'btn btn-default navbar-btn' %>
          <% else %>
            <div class="btn-group">
              <%= link_to "Sign Up", signup_path, class: is_active?(signup_path, "btn btn-default navbar-btn") %>
              <%= link_to "Log In", login_path, class: is_active?(login_path, "btn btn-default navbar-btn") %>
            </div>
          <% end %>
	    </div>
      </div>
    </div>
  </div>                  <!-- end of NavBar -->
  <div class="container">
    <%= yield %>	
  </div>
</body>
</html>

app/views/users/new.html.erb
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %> 
    </div>
    <div class='field'>
      <%= f.label :email %>
      <%= f.text_field :email %> 
    </div>
    <div class='field'>
      <%= f.label :password %>
      <%= f.password_field :password %> 
    </div>
    <div class='field'>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %> 
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>

app/views/welcome/index.html.erb
  <div class="row">
    <h2 class="text-center">Welcome to Wikiful</h2>
  </div>
  <div class="row">
    <div class="col-md-offset-1 col-md-9 col-md-push-2 ">
	  <h5>Recent Stuff</h5>
	  <% @recent_articles.each do |article| %>
	  <div class="thumbnail">
		<div class="caption">
	    <h3><%= link_to article.title, article %></h3>
	    <p><strong>Published:</strong> <em><%= article.created_at.strftime('%d, %b, %Y') %></em>&nbsp;&nbsp;&nbsp;
	    <strong>Category:</strong> <% article.categories.each do |category| %>
	                             <em><%= link_to category.name, category %></em>&nbsp;
	                               <% end %></p>
	      <p><%= truncate(article.content, length: 100) %></p>
	    </div>
	  </div>
	  <% end %>
    </div>
    <div class="col-md-2 col-md-pull-10 sidebar">
      <div class="categories-sidebar">
  	    <div class="btn-group-vertical">
        <h4 class="btn btn-default disabled">Categories</h4>
          <% @categories.each do |category| %>
            <%= link_to category.name, category, class: is_active?(category, "btn btn-default") %>
          <% end %>
          </div>
  	  </div>
    </div>
  </div>